//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgendaMember
    {
        public int MemberId { get; set; }
        public string FirstNamme { get; set; }
        public string LastName { get; set; }
        public string Phonenumber { get; set; }
    }
}
